Add dependency on JSR 305 2.0.3 to find @Nonnull annotation.
SLF4J 1.7.8 added JSR 305's @Nonnull annotation to LoggerFactory [1]
and added an optional dependency on com.google.code.findbugs's jsr305
artifact version 2.0.1 [2], but optional dependencies are not used in
dependent projects [3], so add an explicit dependency on jsr305, but
use version 2.0.3, which is the latest in the 2.0.x series [4].

$ sbt +compile
[info] Loading project definition from project
[info] Set current project to scala-migrations (in build file:)
[info] Setting version to 2.9.0
[info] Reapplying settings...
[info] Set current project to scala-migrations (in build file:)
[info] Updating {file:}scala-migrations...
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[info] Done updating.
[info] Compiling 27 Scala sources to target/scala-2.9.0/classes...
[error] error while loading LoggerFactory, Missing dependency 'class javax.annotation.Nonnull', required by /home/blair/.ivy2/cache/org.slf4j/slf4j-api/jars/slf4j-api-1.7.8.jar(org/slf4j/LoggerFactory.class)
[error] src/main/scala/com/imageworks/migration/ColumnDefinition.scala:87: value getLogger is not a member of object org.slf4j.LoggerFactory
[error]   private final val logger = LoggerFactory.getLogger(this.getClass)
[error]                                            ^
[error] src/main/scala/com/imageworks/migration/DatabaseAdapter.scala:81: value getLogger is not a member of object org.slf4j.LoggerFactory
[error]   protected final val logger = LoggerFactory.getLogger(this.getClass)
[error]                                              ^
[error] src/main/scala/com/imageworks/migration/Migration.scala:69: value getLogger is not a member of object org.slf4j.LoggerFactory
[error]   private final val logger = LoggerFactory.getLogger(this.getClass)
[error]                                            ^
[error] src/main/scala/com/imageworks/migration/Migrator.scala:399: value getLogger is not a member of object org.slf4j.LoggerFactory
[error]   private final val logger = LoggerFactory.getLogger(this.getClass)
[error]                                            ^
[error] src/main/scala/com/imageworks/migration/With.scala:53: value getLogger is not a member of object org.slf4j.LoggerFactory
[error]   private final val logger = LoggerFactory.getLogger(this.getClass)
[error]                                            ^
[error] 6 errors found
[error] (compile:compile) Compilation failed

[1] http://www.slf4j.org/news.html
[2] http://repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.8/slf4j-api-1.7.8.pom
[3] http://maven.apache.org/guides/introduction/introduction-to-optional-and-excludes-dependencies.html
[4] http://mvnrepository.com/artifact/com.google.code.findbugs/jsr305

Change-Id: Ibe40bd4ab236745b17611cee1e7ed5dc394307cb