Switch PostgreSQL unit tests to "public" schema to fix failures.
With the previous configuration, the PostgreSQL unit tests used a
database named "test" and a schema named "test".  However, even after
creating the "test" schema in the "test" database the unit tests
failed with the below exception.

Without qualifying a table's name with the schema name, PostgreSQL
defaults to using the "public" schema, so while migrations were
properly creating tables in the "test" schema some unit tests were
failing because they were using bare table names which defaulted to
being in the "public" schema.

1) Add a new "scala-migrations.db.db" Java property with the name of
   the database to use; defaults to "test".
2) For the PostgreSQL configuration, change the default value of the
   "scala-migrations.db.schema" Java property to "public".

[info] Test com.imageworks.migration.tests.MigrationTests.duplicateDescriptionsThrows started
[error] Test com.imageworks.migration.tests.MigrationTests.duplicateDescriptionsThrows failed: Unexpected exception, expected<com.imageworks.migration.DuplicateMigrationDescriptionException> but was<org.postgresql.util.PSQLException>
[error]     at com.novocode.junit.JUnitRunner.run(JUnitRunner.java:89)
[error]     at sbt.TestRunner.delegateRun(TestFramework.scala:58)
[error]     at sbt.TestRunner.run(TestFramework.scala:51)
[error]     at sbt.TestRunner.runTest$1(TestFramework.scala:71)
[error]     at sbt.TestRunner.run(TestFramework.scala:80)
[error]     at sbt.TestFramework$$anonfun$6$$anonfun$apply$8$$anonfun$7$$anonfun$apply$9.apply(TestFramework.scala:178)
[error]     at sbt.TestFramework$$anonfun$6$$anonfun$apply$8$$anonfun$7$$anonfun$apply$9.apply(TestFramework.scala:178)
[error]     at sbt.TestFramework$.sbt$TestFramework$$withContextLoader(TestFramework.scala:190)
[error]     at sbt.TestFramework$$anonfun$6$$anonfun$apply$8$$anonfun$7.apply(TestFramework.scala:178)
[error]     at sbt.TestFramework$$anonfun$6$$anonfun$apply$8$$anonfun$7.apply(TestFramework.scala:178)
[error]     at sbt.Tests$$anonfun$makeSerial$1$$anonfun$apply$8.apply(Tests.scala:121)
[error]     at sbt.Tests$$anonfun$makeSerial$1$$anonfun$apply$8.apply(Tests.scala:121)
[error]     at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:233)
[error]     at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:233)
[error]     at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:59)
[error]     at scala.collection.immutable.List.foreach(List.scala:76)
[error]     at scala.collection.TraversableLike$class.map(TraversableLike.scala:233)
[error]     at scala.collection.immutable.List.map(List.scala:76)
[error]     at sbt.Tests$$anonfun$makeSerial$1.apply(Tests.scala:121)
[error]     at sbt.Tests$$anonfun$makeSerial$1.apply(Tests.scala:121)
[error]     at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:47)
[error]     at sbt.std.Transform$$anon$3$$anonfun$apply$2.apply(System.scala:47)
[error]     at sbt.std.Transform$$anon$5.work(System.scala:71)
[error]     at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:232)
[error]     at sbt.Execute$$anonfun$submit$1$$anonfun$apply$1.apply(Execute.scala:232)
[error]     at sbt.ErrorHandling$.wideConvert(ErrorHandling.scala:18)
[error]     at sbt.Execute.work(Execute.scala:238)
[error]     at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:232)
[error]     at sbt.Execute$$anonfun$submit$1.apply(Execute.scala:232)
[error]     at sbt.ConcurrentRestrictions$$anon$4$$anonfun$1.apply(ConcurrentRestrictions.scala:159)
[error]     at sbt.CompletionService$$anon$2.call(CompletionService.scala:30)
[error]     at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
[error]     at java.util.concurrent.FutureTask.run(FutureTask.java:138)
[error]     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:441)
[error]     at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
[error]     at java.util.concurrent.FutureTask.run(FutureTask.java:138)
[error]     at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:886)
[error]     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:908)
[error]     at java.lang.Thread.run(Thread.java:662)
[error] Caused by: org.postgresql.util.PSQLException: ERROR: schema "test" does not exist
[error]     at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2102)
[error]     at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:1835)
[error]     at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:257)
[error]     at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:500)
[error]     at org.postgresql.jdbc2.AbstractJdbc2Statement.executeWithFlags(AbstractJdbc2Statement.java:374)
[error]     at org.postgresql.jdbc2.AbstractJdbc2Statement.execute(AbstractJdbc2Statement.java:366)
[error]     at net.sf.log4jdbc.StatementSpy.execute(StatementSpy.java:813)
[error]     at com.imageworks.migration.Migration$$anonfun$execute$1.apply(Migration.scala:199)
[error]     at com.imageworks.migration.Migration$$anonfun$execute$1.apply(Migration.scala:198)
[error]     at com.imageworks.migration.With$.resource(With.scala:77)
[error]     at com.imageworks.migration.With$.autoClosingStatement(With.scala:221)
[error]     at com.imageworks.migration.Migration.execute(Migration.scala:198)
[error]     at com.imageworks.migration.Migration.createTable(Migration.scala:253)
[error]     at com.imageworks.migration.CreateSchemaMigrationsTableMigration.up(Migrator.scala:62)
[error]     at com.imageworks.migration.Migrator$$anonfun$com$imageworks$migration$Migrator$$runMigration$1.apply(Migrator.scala:557)
[error]     at com.imageworks.migration.Migrator$$anonfun$com$imageworks$migration$Migrator$$runMigration$1.apply(Migrator.scala:551)
[error]     at com.imageworks.migration.Migrator$$anonfun$withConnections$1.apply(Migrator.scala:504)
[error]     at com.imageworks.migration.Migrator$$anonfun$withConnections$1.apply(Migrator.scala:499)
[error]     at com.imageworks.migration.With$$anonfun$autoCommittingConnection$1.apply(With.scala:175)
[error]     at com.imageworks.migration.With$$anonfun$autoCommittingConnection$1.apply(With.scala:172)
[error]     at com.imageworks.migration.With$$anonfun$autoRestoringConnection$2.apply(With.scala:144)
[error]     at com.imageworks.migration.With$$anonfun$autoRestoringConnection$2.apply(With.scala:142)
[error]     at com.imageworks.migration.With$.resource(With.scala:77)
[error]     at com.imageworks.migration.With$.autoRestoringConnection(With.scala:142)
[error]     at com.imageworks.migration.With$.autoCommittingConnection(With.scala:172)
[error]     at com.imageworks.migration.ConnectionBuilder$$anonfun$withConnection$1.apply(ConnectionBuilder.scala:112)
[error]     at com.imageworks.migration.ConnectionBuilder$$anonfun$withConnection$1.apply(ConnectionBuilder.scala:111)
[error]     at com.imageworks.migration.With$.resource(With.scala:77)
[error]     at com.imageworks.migration.With$.autoClosingConnection(With.scala:116)
[error]     at com.imageworks.migration.ConnectionBuilder.withConnection(ConnectionBuilder.scala:111)
[error]     at com.imageworks.migration.Migrator.withConnections(Migrator.scala:499)
[error]     at com.imageworks.migration.Migrator.com$imageworks$migration$Migrator$$runMigration(Migrator.scala:551)
[error]     at com.imageworks.migration.Migrator.initializeSchemaMigrationsTable(Migrator.scala:602)
[error]     at com.imageworks.migration.Migrator.migrate(Migrator.scala:671)
[error]     at com.imageworks.migration.tests.MigrationTests.duplicateDescriptionsThrows(MigrationTests.scala:93)
[error]     ...
[info] Test com.imageworks.migration.tests.MigrationTests.duplicateVersionsThrows started

Change-Id: Idf79ebfa3b2a46616ef5e83d9d1f6765fa9e1a93