Update to SLF4J 1.7.1.
Between 1.6.x and 1.7.x SLF4J's API changed from

  Logger#warn(String format, Object... arguments)

to

  Logger#warn(String format, Object[] argArray)

which requires that : _* be appended to any Array[AnyRef](...)
arguments, otherwise there are compile warnings:

   [scalac] src/main/scala/com/imageworks/migration/ColumnDefinition.scala:180: warning: I'm seeing an array passed into a Java vararg.
   [scalac] I assume that the elements of this array should be passed as individual arguments to the vararg.
   [scalac] Therefore I follow the array with a `: _*', to mark it as a vararg argument.
   [scalac] If that's not what you want, compile this file with option -Xno-varargs-conversion.
   [scalac]                     Array[AnyRef](getColumnName, default.get, value))
   [scalac]                     ^

Additionally, there are compile errors that need to be resolved:

   [scalac] src/main/scala/com/imageworks/migration/ColumnDefinition.scala:410: error: ambiguous reference to overloaded definition,
   [scalac] both method warn in trait Logger of type (java.lang.String,Any,Any)Unit
   [scalac] and  method warn in trait Logger of type (java.lang.String,java.lang.Object*)Unit
   [scalac] match argument types (java.lang.String,String,List[com.imageworks.migration.ColumnOption]) and expected result type Unit
   [scalac]       logger.warn("The following options for the '{}' column are unused: {}.",
   [scalac]              ^

While this is a source change, in my testing, SLF4J is binary
compatible between 1.5.8 and 1.7.1, compiled Scala Migrations jars
continue to work with either 1.5.8 or 1.7.1.  To test binary
compatibility, I compiled against 1.5.8 and tested with 1.7.1 and then
compiled against 1.7.1 and tested with 1.5.8; all unit tests passed.