Prepare for MySQL by using shorter foreign key constraint names.
The unit test fails with the following exception:

  com.mysql.jdbc.exceptions.jdbc4.MySQLSyntaxErrorException: Identifier name
  'fk_scala_migrations_people_pk_scala_migrations_location_scala_migrations_location_pk_scala_migration'
  is too long

Specify the foreign key constraint name making the following
replacements in the original constraint name:

  s/scala_migrations_location/sml/g
  s/scala_migrations_people/smp/g

Additionally, use these same replacements for the index on
scala_migrations_people.pk_scala_migrations_location.

Change-Id: I0038103cfee6a4c87b2b4cedf02a9465d33f33f7