TestDatabase.scala: add Derby 10.11.1.1 and drop JDBC 3 support.
Compiling against Derby 10.11.1.1 generates this compile error:

[info] Compiling 23 Scala sources to /var/lib/jenkins/tomcat7/jenkins/jobs/scala-migrations-gerrit/workspace/target/scala-2.9.0/test-classes...
[error] /var/lib/jenkins/tomcat7/jenkins/jobs/scala-migrations-gerrit/workspace/src/test/scala/com/imageworks/migration/tests/TestDatabase.scala:169: type EmbedSQLException is not a member of package org.apache.derby.impl.jdbc
[error]     case _: org.apache.derby.impl.jdbc.EmbedSQLException =>
[error]                                        ^
[error] one error found

This appears to be due to the removal of EmbedSQLException in
10.11.1.1 [1].  Given that EmbedSQLException is only used in JDBC 3
version of the driver and JDBC 4 was released with JDK 1.6 which is
now a deprecated Java version, remove JDBC 3 support.

[1] https://issues.apache.org/jira/browse/DERBY-6488 .

Change-Id: I5cd6383a73d933e22718b998d7b914f6af31fecc